# Generated by Django 4.0.4 on 2022-04-13 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pastemployee_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastemployee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
